export { default as HomePage } from './HomePage';
export { default as ProductsPage } from './ProductsPage';
export { default as ProductDetailPage } from './ProductDetailPage';
export { default as ProductCreatePage } from './ProductCreatePage';
export { default as AboutPage } from './AboutPage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as DashboardPage } from './DashboardPage';